### PR TITLE
Supla-server logging to local volume

### PR DESCRIPTION
**Pull request by karolszklarski**

### CODE REVIEW

**Comment by fracz** [comment]
LGTM. @przemyslawzygmunt is the `/var/log/supla` the only directory with supla-server log files?

**Comment by przemyslawzygmunt** [comment]
It depends on the [r]syslog.conf configuration. I suggest to redirect whole /var/log. Will be usefull.

**Comment by fracz** [comment]
I have just checked a supla-server instance and there is no `/var/log/supla` at all. In container configuration there is a redirection of supla-server logs to docker logs: https://github.com/SUPLA/supla-docker/blob/src/server/supervisord.conf#L6-L9

@karolszklarski are have you tested this configuration?

**Comment by karolszklarski** [comment]
Ha. You're right. I forgot I have a modified docker image. I'll fix that tomorrow.

`
root@30ae5a8f57a9:/etc/supervisor/conf.d# cat supervisord.conf 
[supervisord]
nodaemon = true

[program:supla-server]
command = /usr/local/bin/supla-server
stdout_logfile=/var/log/supla/supla-server.log
stdout_logfile_maxbytes=0
stderr_logfile=/var/log/supla/supla-server.log
stderr_logfile_maxbytes=0
autorestart = true

[program:supla-scheduler]
command = /usr/local/bin/supla-scheduler
stdout_logfile=/var/log/supla/supla-scheduler.log
stdout_logfile_maxbytes=0
stderr_logfile=/var/log/supla/supla-scheduler.log
stderr_logfile_maxbytes=0
autorestart = true
`

**Comment by fracz** [comment]
I don't think it's a good idea. Docker logs can be easily checked with `docker logs CONTAINER` command. What's more Docker takes care about log size automatically. IMO the current config is the best.

**Pull request closed without merging**
